[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
airdrop_token = "7EgdiV19pAuWNbFHrMGpwsEt9AqyxmsrhRkp5nWEPaqb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/buithinh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
